spring.application.name=HealthMVC

spring.mongodb.uri=mongodb+srv://db_admin:${DB_PASSWORD}@dev-spring-security-hea.74zfj0o.mongodb.net/
spring.mongodb.database=healthapp
spring.data.mongodb.auto-index-creation=true
management.health.mongodb.enabled=false
